server:
  port: 2222

spring:
  application:
    name: CLOUD-API-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

      routes:
        - id: greet-api
          uri: lb://GREET-API
          predicates:
            - Path=/greet

        - id: welcome-api
          uri: lb://WELCOME-API
          predicates:
            - Path=/welcome
